### ISSUE TITLE
"make deps" runs yay as sudo

### ISSUE THREAD

**Issue by xCloudK** [ozwaldorf/dotfiles#3]
When running the make deps command after cd'ing into the cloned repo, it outputs the yay command which is sudo yay -S {all the pkgs}.
 Because yay is run as sudo it doesn't install packages. You can get around this by manually installing the packages using yay or paru but its probably better to change the script to run yay as normal user

**Comment by ozwaldorf** [comment]
Fair point, thanks for the report!

**Comment by ozwaldorf** [comment]
Lmk if theres any other issues!
